package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallVipCard;
import org.linlinjava.litemall.db.domain.LitemallVipCardExample;

public interface LitemallVipCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    long countByExample(LitemallVipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallVipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    int insert(LitemallVipCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    int insertSelective(LitemallVipCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    LitemallVipCard selectOneByExample(LitemallVipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    LitemallVipCard selectOneByExampleSelective(@Param("example") LitemallVipCardExample example, @Param("selective") LitemallVipCard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    LitemallVipCard selectOneByExampleWithBLOBs(LitemallVipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    List<LitemallVipCard> selectByExampleSelective(@Param("example") LitemallVipCardExample example, @Param("selective") LitemallVipCard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    List<LitemallVipCard> selectByExampleWithBLOBs(LitemallVipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    List<LitemallVipCard> selectByExample(LitemallVipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    LitemallVipCard selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallVipCard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    LitemallVipCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallVipCard record, @Param("example") LitemallVipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallVipCard record, @Param("example") LitemallVipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallVipCard record, @Param("example") LitemallVipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallVipCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallVipCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallVipCard record);
}