package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserPointDetail;
import org.linlinjava.litemall.db.domain.LitemallUserPointDetailExample;

public interface LitemallUserPointDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserPointDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserPointDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    int insert(LitemallUserPointDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserPointDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    LitemallUserPointDetail selectOneByExample(LitemallUserPointDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    LitemallUserPointDetail selectOneByExampleSelective(@Param("example") LitemallUserPointDetailExample example, @Param("selective") LitemallUserPointDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    List<LitemallUserPointDetail> selectByExampleSelective(@Param("example") LitemallUserPointDetailExample example, @Param("selective") LitemallUserPointDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    List<LitemallUserPointDetail> selectByExample(LitemallUserPointDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    LitemallUserPointDetail selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserPointDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    LitemallUserPointDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserPointDetail record, @Param("example") LitemallUserPointDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserPointDetail record, @Param("example") LitemallUserPointDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserPointDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_point_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserPointDetail record);
}